# Generated by Django 3.1.5 on 2021-01-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
