# Generated by Django 3.1.5 on 2021-02-10 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210116_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
