# Generated by Django 3.1.5 on 2021-02-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
